### ISSUE TITLE
Chrome Version 115.0.5790.102 seems to have broken positioning...

### ISSUE THREAD

**Issue by cosmoKenney** [MrFrankel/ngx-popper#180]
@MrFrankel,
I am on windows 11, chrome just updated to Version 115.0.5790.102 last night or this morning. Edge and Firefox are okay.
Edge: 
![edge-popper](https://github.com/MrFrankel/ngx-popper/assets/3654426/bb6bf8f6-2605-4c6b-9e08-2a10319b09b2)
Chrome:
![chrome-popper](https://github.com/MrFrankel/ngx-popper/assets/3654426/7530e753-8dcf-4317-b2bc-5d3517338a08)
Oddly, after resizing chrome a few pixels, either horizontally or vertically, the popper jumps back to the left, but goes too far:
![chrome-popper-after-resize](https://github.com/MrFrankel/ngx-popper/assets/3654426/7ef7cb63-ba60-4663-a45f-40e852e4589e)

**Comment by cosmoKenney** [comment]
Note, I am also using Tippy.js (for tool-tips) which depends on @popperjs/core. The positioning of Tippy not effected as far as I can tell.  
Chrome Tippy:
![chrome-tippy](https://github.com/MrFrankel/ngx-popper/assets/3654426/294bb82d-52b1-49ed-8d91-3b548312828a)

**Comment by vedd** [comment]
I am also facing the same issue

**Comment by gertot** [comment]
this may help

```css
popper-content {
    .ngxp__container {
        display: block!important;
        position: absolute;
        left: 0;
        top: 0;
        opacity: 0;

        &[aria-hidden="true"] {
            visibility: hidden;
        }
    }
}
```
